# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TUMOZMS76c3ny8w7yRPsS6Nw4JV4Jgw7
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Titanic dataset load
df = sns.load_dataset('titanic')
df.head()

print(df.describe())
print("\nMissing values:")
print(df.isnull().sum())

plt.figure(figsize=(12,4))

plt.subplot(1,2,1)
sns.histplot(df['age'].dropna(), bins=30, kde=True, color='skyblue')
plt.title('Age Distribution')

plt.subplot(1,2,2)
sns.histplot(df['fare'], bins=40, kde=True, color='salmon')
plt.title('Fare Distribution')

plt.show()

plt.figure(figsize=(12,4))

plt.subplot(1,2,1)
sns.boxplot(x=df['age'], color='skyblue')
plt.title('Age Boxplot - Outliers')

plt.subplot(1,2,2)
sns.boxplot(x=df['fare'], color='salmon')
plt.title('Fare Boxplot - Outliers')

plt.show()

sns.pairplot(df[['survived','pclass','age','fare']].dropna(), hue='survived', palette='Set1')
plt.show()

print("\nPattern 1: Pclass 1 madhe survival jast")
print(df.groupby('pclass')['survived'].mean())
print("\nPattern 2: Female survival jast")
print(df.groupby('sex')['survived'].mean())